[build.environment]
  NODE_VERSION = "20"

[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
